config/routes.rb
Rails.application.routes.draw do
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  post 'choice', to: 'sessions#choice', as: 'choice'
  get 'query', to: "queries#create", as: 'query'

  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]
  get 'users/:id/groups' => 'users#groups', as: 'user_groups'
  resources :users, only: [:show, :index]
  resources :resources
  resources :groups
  resources :comments, only: [:create, :destroy]
  resources :google_docs, only: [:create, :destroy]
  resources :favorites, only: [:index, :create, :destroy]
  resources :teachers, only: [:show]
  resources :videos
  resources :notifications, only: [:create, :index, :destroy]
  resources :friendships, only: [:create, :destroy]
  resources :user_groups, only: [:create, :destroy]
 
  root to: "home#show"

end

app/models/group.rb
# == Schema Information
#
# Table name: groups
#
#  id          :integer          not null, primary key
#  topic       :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  description :text
#

class Group < ActiveRecord::Base
  include PublicActivity::Model
  tracked only: :create, owner: Proc.new { |controller, model| controller.current_user ? controller.current_user : nil }

  has_many :user_groups
  has_many :users, through: :user_groups
  has_many :students, through: :users
  has_many :teachers, through: :users
  has_many :comments, through: :resources
  has_many :resources
  has_many :google_docs
  has_many :videos
  has_many :favorites, through: :resources
  has_many :notifications
  validates :topic, presence: true

  def self.most_resources
    self.joins(:resources).select('groups.*, COUNT(resources.id) as resources_count').group('groups.id').order('resources_count DESC').limit(10)
  end

  def comments_over_time
    comments_over_time_hash = comments.group_by{|comment| comment.created_at.to_date.to_s }
    comments_over_time_array = comments_over_time_hash.map{|k,v| [k, v.length]}
    comments_over_time_array.unshift([(self.created_at - 1.day).to_date.to_s, 0])
    return comments_over_time_array
  end

  def add_member(user)
    if !self.users.include?(user)
      self.users << user 
    end
  end

  def remove_member(user)
    self.users.delete(user) if self.users.include?(user)
  end

  def members
    self.users.each_with_object([]) do |user, array|
      array << {name: user.gmail_name, email: user.email}
    end  
  end 

  def invite_ids(current_user)
    # nonmembers = UserGroup.where.not(group_id: self.id).pluck(:user_id)
    # nonmembers.select{|id| current_user.friend_ids.include?(id)}
    User.all.select{|user| !self.users.include?(user) && current_user.friend_ids.include?(user.id)}
  end

  def user_emails(current_user)
    emails = self.users.pluck(:email)
    emails.delete(current_user.email)
    emails.join(",")
  end




end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :login_required

  def show
    @group = Group.find(params[:id])
    @resource = Resource.new
    @google_doc = GoogleDoc.new
    @video = Video.new
    @notification = Notification.new
    @comments_over_time = @group.comments_over_time
    @invite_list = @group.invite_ids(current_user)
    @user_group = UserGroup.find_by(group_id: @group.id, user_id: current_user.id)
    respond_to do |format| 
      format.html
      format.json {render json: {comments_over_time: @comments_over_time}}
    end
  end

  def index
    @groups = Group.all
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.save!
    current_user.groups << @group
    redirect_to group_path(@group)
    rescue ActiveRecord::RecordInvalid
      render 'new'
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    @group.update(group_params)    
    redirect_to @group
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    redirect_to groups_path
  end

  private

  def group_params
    params.require(:group).permit(:topic, :description)
  end

end

app/views/groups/_form.html.erb
<%= form_for @group do |f| %>
<div class="field form-group">
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h4><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h4>

      <ul>
      <% @group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :topic %>
  <%= f.text_field :topic, class: 'form-control' %>
</div>
<div class="field form-group">
  <%= f.label :description %>
  <%= f.text_area :description, class: 'form-control' %>
</div>
  <%= f.submit "Add Group", class: "btn btn-default" %>
<% end %>

app/views/groups/_group.html.erb
<tr class="resource-row-js">
  <td class="col-md-4"><%= link_to group.topic, group_path(group) %></td>
  <td class="col-md-2"><%= group.description %></td>
  <td class="col-md-4"><%= render partial: JoinGroupOptions.new(group, current_user).member?, locals: {group: group, user_group: group.user_groups.where(user_id: current_user.id).first} %></td>
</tr>

app/views/groups/_join_group_options.html.erb
<%= button_to "Join Group", {controller: "user_groups", action: "create", group_id: group.id}, {method: :post, class: "btn btn-success btn-xs"} %>

app/views/groups/_leave_group_options.html.erb
<%= button_to "Leave Group", user_group_path(user_group), method: :delete, class: "btn btn-primary btn-xs" %>

app/views/groups/_query_results.html.erb
<tr>
  <td><%= link_to article.title, article.link, :target => "_blank" %></td>
  <td><%= form_for Resource.new, remote: true, html:{class: "save-resource-btn"} do |f| %>
    <%= f.hidden_field :title, value: article.title %>
    <%= f.hidden_field :link, value: article.link %>
    <%= f.hidden_field :group_id, value: group_id %>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.submit "Save", class: "btn btn-default btn-xs" %>
  <% end %></td>
</tr>

app/views/groups/edit.html.erb
<h3>Edit Group</h3>
<div class="row">
  <div class="col-md-6">
    <%= render 'form' %>
  </div>
</div>

app/views/groups/index.html.erb
<h3>All Groups</h3>

<%= link_to "Add New Group", new_group_path %><br><br>

<%= render "shared/search_form" %>

<br>
<table class="table table-striped filterable-table">
  <tr>
    <th class="col-md-4"><strong>Name</strong></th>
    <th class="col-md-4"><strong>Description</strong></th>
    <th class="col-md-4"><strong>Options</strong></th>
  </tr>
<% @groups.each do |group| %>
  <%= render partial: 'groups/group', locals: {group: group, current_user: current_user} %>
<% end %>
</table>

app/views/groups/new.html.erb
<h3>New Group</h3>

<div class="row">
  <div class="col-md-6">
    <%= render 'form' %>
  </div>
</div>

app/views/groups/show.html.erb
<h3>Group Topic: <%= @group.topic %></h3>
<p>Description: <%= @group.description %></p>
<p><%= render partial: JoinGroupOptions.new(@group, current_user).member?, locals: {group: @group, user_group: @user_group} %></p>

<% if current_user.groups.include?(@group) %>
<div class="row">
  <div class="col-md-3">
    <h3>Get Started</h3>
    <p>Search the <em>New York Times</em> for relevant articles here.</p>
    <%= form_tag("/query", method: "get", remote: true, id: "article-search") do %>
      <div class="input-group">
        <%= hidden_field_tag(:group_id, @group.id) %>
        <%= text_field_tag 'q', '', class: 'form-control' %>
        <span class="input-group-btn" id="basic-addon2"><%= submit_tag("Search", class: "btn btn-primary") %></span>
      </div>
    <% end %>
    <h4>Results</h4>
    <%= link_to "Clear", "#", id:"clear-search-results-button", class: "btn btn-primary" %>

    <div id="article-results">
      <table class="table">
        <tbody>
        </tbody>
      </table>
    </div>
  </div>
  <div class="col-md-6">
    <!-- begin panel -->
    <div>
      <!-- Nav tabs -->
      <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active"><a href="#members" aria-controls="members" role="tab" data-toggle="tab">Members</a></li>
        <li role="presentation"><a href="#resources" aria-controls="resources" role="tab" data-toggle="tab">Resources</a></li>
        <li role="presentation"><a href="#videos" aria-controls="videos" role="tab" data-toggle="tab">Videos</a></li>
        <li role="presentation"><a href="#documents" aria-controls="documents" role="tab" data-toggle="tab">Documents</a></li>
        <li role="presentation"><a href="#comments-over-time" aria-controls="documents" role="tab" data-toggle="tab">Comments/Time</a></li>
      </ul>
      <!-- Tab panes -->
      <div class="tab-content">
        <div role="tabpanel" class="tab-pane active" id="members">
          <h4>Group Members</h4>
          <ul>
            <% @group.users.each do |user| %>
              <li><%= user.gmail_name %></li>
            <% end %>
          </ul>
          <% if @group.users.length > 1 %>
          <%= mail_to @group.user_emails(current_user), "Email All Members", subject: @group.topic, class: "btn btn-info btn-xs" %>
          <% end %>
          
        </div>
        <div role="tabpanel" class="tab-pane" id="resources">
          <h4>Resources</h4>
            <table class="table table-striped resources-container">
              <% @group.resources.each do |resource| %>
                <%= render 'resources/resource', {resource: resource, current_user: current_user} %>
              <% end %>
            </table>
        </div>
        <div role="tabpanel" class="tab-pane" id="videos">
          <h4>Videos</h4>
          <table class="table table-striped videos-container">
            <% @group.videos.each do |video| %>
              <%= render 'videos/video', {video: video, current_user: current_user} %>
            <% end %>
          </table>
        </div>
        <div role="tabpanel" class="tab-pane" id="documents">
          <h4>Our Docs</h4>
           <table class='table' id='google_doc_table'>
            <thead>
              <tr>
                <th>Document Name</th>
              </tr>
            </thead>
            <tbody>
              <% @group.google_docs.each do |google_doc| %>
                <%= render partial: 'google_docs/table_row', locals: {google_doc: google_doc} %>
              <% end %>
            </tbody>
          </table>
        </div>
        <div role="tabpanel" class="tab-pane" id="comments-over-time">
          <div id="loading-message" style="display: none;">
            <center><h4>Loading</h4></center>
            <%= image_tag("ajax-loader.gif", id: "loading-gif") %>

        </div>
          </div>
        </div>
    </div><!-- end panel -->
  </div>
  <div class="col-md-3">
    <h4>Invite a User to this Group</h4>
      <%= form_for @notification do |f| %>
        <%= f.collection_select :user_id, @invite_list, :id, :gmail_name, {:prompt => "Select a user",}, {class: "form-control"} %>
        <%= f.hidden_field :group_id, value: @group.id %>
        <%= f.hidden_field :sender_name, value: current_user.gmail_name %>
        <br>
        <%= f.submit "Invite", class: "btn btn-primary"%>
      <% end %>
      <p></p><br>

    <h4>Add New Resources</h4>
    <ul class="list-group" id="display-box-options">
      <li class="list-group-item">
        <%= link_to 'New Resource', '#new_resource_modal', 'data-toggle' => 'modal' %>
      </li>
      <li class="list-group-item">
        <%= link_to 'New Video', '#new_video_modal', 'data-toggle' => 'modal' %>
      </li>
      <li class="list-group-item">
        <%= link_to 'New Google Doc', '#new_google_doc_modal', 'data-toggle' => 'modal' %>
      </li>
    </ul>
  </div>  
</div>

<div class="modal fade" id="new_google_doc_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Create new Google Doc</h4>
      </div>
      <div class="modal-body">
        <%= render 'google_docs/form', group_id: @group.id, modal: true %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>


<div class="modal fade" id="new_video_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Link to YouTube Video</h4>
      </div>
      <div class="modal-body">
        <%= render 'videos/form', group_id: @group.id, modal: true %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="new_resource_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Link to New Resource</h4>
      </div>
      <div class="modal-body">
        <%= render 'resources/form', group_id: @group.id, modal: true %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>


</div>
<% end %>