config/routes.rb
Rails.application.routes.draw do
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  post 'choice', to: 'sessions#choice', as: 'choice'
  get 'query', to: "queries#create", as: 'query'

  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]
  get 'users/:id/groups' => 'users#groups', as: 'user_groups'
  resources :users, only: [:show, :index]
  resources :resources
  resources :groups
  resources :comments, only: [:create, :destroy]
  resources :google_docs, only: [:create, :destroy]
  resources :favorites, only: [:index, :create, :destroy]
  resources :teachers, only: [:show]
  resources :videos
  resources :notifications, only: [:create, :index, :destroy]
  resources :friendships, only: [:create, :destroy]
  resources :user_groups, only: [:create, :destroy]
 
  root to: "home#show"

end

app/models/video.rb
# == Schema Information
#
# Table name: videos
#
#  id           :integer          not null, primary key
#  link         :string
#  title        :string
#  published_at :datetime
#  likes        :integer
#  dislikes     :integer
#  uid          :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  group_id     :integer
#  user_id      :integer
#

class Video < ActiveRecord::Base

  belongs_to :group
  belongs_to :user
  
  YT_LINK_FORMAT = /\A.*(youtu.be\/|v\/|u\/\w\/|embed\/|watch\?v=|\&v=)([^#\&\?]*).*/i

  validates :link, presence: true, format: YT_LINK_FORMAT
  
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def index
    @videos = Video.order('created_at DESC')
  end

  def create
    @video = Video.new(video_params)
    @video.user_id = current_user.id
    if @video.save
      video_item = render_to_string(partial: 'videos/video', locals: {video: @video})
      render json: {video_item: video_item}
    else
      render json: {errors: @video.errors.full_messages}, status: 422
    end 
  end

  def destroy
    @video = Video.find(params[:id])
    @video.destroy
    render json: {message: "destroyed"}
  end 

  private

  def video_params
    params.require(:video).permit(:link, :group_id, :user_id)
  end
end

app/views/videos/_form.html.erb
<% modal ||= false %>
<% remote = modal ? true : false %>
<%= form_for @video, remote: remote, html: {class: "form-inline", role: :form, 'data-model' => 'youtube_video', id: 'new_video_form'} do |f| %>
  <div id="video_errors">
  </div>

  <div class="form-group" id="new_video_body">
    <%= f.label :link %>
    <%= f.text_field :link, class: 'form-control', required: true %>
    <%= f.hidden_field :group_id, value: group_id %>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.submit class: 'btn btn-primary' %>
  <% end %>
  </div>

app/views/videos/_video.html.erb
<tr>
  <td class="col-md-9">
    <%= link_to "#{video.title}", "#{video.link}" %>
  </td>
  <td class="col-md-3">
    <% if video.user_id == current_user.id %>
         <%= link_to("X", video_path(video), method: :delete, remote: true, class: "destroy-video-js") %>
    <% end %>
  </td>
</tr>

app/views/videos/index.html.erb
<div class="jumbotron">
  <div class="container">
    <h1>Your Videos</h1>
    <% if current_user.videos.any? %>

  <div class="container">
    <div id="player-wrapper"></div>
    <% current_user.videos.each do |video| %>
      <div class="row">
          <% if video %>
            <div class="col-md-4">
              <div class="yt_video thumbnail">
                <%= link_to image_tag("https://img.youtube.com/vi/#{video.uid}/mqdefault.jpg", alt: video.title,
                                      class: 'img-rounded'),
                            "https://www.youtube.com/watch?v=#{video.uid}", target: '_blank' %>
                <div class="caption">
                  <h5><%= video.title %></h5>
                  <p>Published on <%= video.published_at.strftime('%-d %B %Y') %></p>
                  <p>
                    <span class="glyphicon glyphicon glyphicon-thumbs-up"></span> <%= video.likes %>
                    <span class="glyphicon glyphicon glyphicon-thumbs-down"></span> <%= video.dislikes %>
                  </p>
                </div>
              </div>
            </div>
          <% end %>
      </div>
    <% end %>
  </div>
<% end %>


  </div>
</div>