config/routes.rb
Rails.application.routes.draw do
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  post 'choice', to: 'sessions#choice', as: 'choice'
  get 'query', to: "queries#create", as: 'query'

  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]
  get 'users/:id/groups' => 'users#groups', as: 'user_groups'
  resources :users, only: [:show, :index]
  resources :resources
  resources :groups
  resources :comments, only: [:create, :destroy]
  resources :google_docs, only: [:create, :destroy]
  resources :favorites, only: [:index, :create, :destroy]
  resources :teachers, only: [:show]
  resources :videos
  resources :notifications, only: [:create, :index, :destroy]
  resources :friendships, only: [:create, :destroy]
  resources :user_groups, only: [:create, :destroy]
 
  root to: "home#show"

end

app/views/resources/_favorite_resource.html.erb
<%= link_to favorites_path(group_id: resource.group.id, resource_id: resource.id), method: :post, remote: true, class: "btn btn-primary btn-xs favorite" do %>
  <i class="fa fa-magic"></i> Favorite
<% end %>

app/views/resources/_form.html.erb
<% modal ||= false %>
<% remote = modal ? true : false %>
<%= form_for @resource, remote: remote, html: {class: "form-inline", role: :form, 'data-model' => 'resource', id: "new_resource_form"} do |f| %>
    <div id="resource_errors">
      
    </div>
  <div class="form-group" id="new_resource_body">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
    <%= f.label :link %>
    <%= f.text_field :link, class: "form-control" %>
    <p class="help-block">Links must start with 'http://' or 'https://'</p>
    <%= f.hidden_field :group_id, value: group_id %>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <p></p>
  <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/resources/_resource.html.erb
<tr class="resource-row-js">
  <td class="col-md-4"><%= link_to resource.title, resource %></td>
  <td class="col-md-1"><%= link_to "View", resource.link, target: "_blank" %></td>
  <td class="col-md-4"><%= resource.likes_message(current_user) %></td>
  <td class="col-md-2"><%= render partial: "/resources/#{FavoriteToggle.new(resource, current_user).already_favorited?}", locals: {resource: resource} %></td>
   <td class="col-md-1">
    <% if resource.user_id == current_user.id %>
     <%= link_to("X", resource_path(resource), method: :delete, remote: true, class: "destroy-resource-js") %>
    <% end %>
    </td>
</tr>

app/views/resources/_unfavorite_resource.html.erb
<%= link_to favorite_path(resource.favorites.where(user_id: current_user.id).first), method: :delete, remote: true, class: "btn btn-primary btn-xs unfavorite" do %>
  <i class="fa fa-magic"></i> Unfavorite
<% end %>

app/views/resources/edit.html.erb
<h3>Edit Resource</h3>

<%= render 'form', group_id: @resource.group.id %>

app/views/resources/index.html.erb
<h3>My Resources</h3>
<br>
<%= render "shared/search_form" %>
<br>
<% @resources_by_group.each do |group_resources| %>
  <h4>Group: <%= link_to group_resources[0].topic, group_resources[0] %></h4>
  <table class="table table-striped resources-container filterable-table">
    <% group_resources[1].each do |resource| %> 
      <%= render 'resources/resource', {resource: resource, current_user: current_user} %>
    <% end %> 
  </table>
<% end %>
</ul>

app/views/resources/show.html.erb
<div class="row">
  <h3>Title: <%=@resource.title%></h3>
  <div class="resources-container">
  <%= render partial: FavoriteToggle.new(@resource, current_user).already_favorited?, locals: {resource: @resource} %>
  </div><br>
  <%= link_to "Click to Edit", edit_resource_path(@resource), class: "btn btn-info" %>
  <p>Link: <a href="<%= @resource.link %>" target="_blank"><%= @resource.link %> </a></p>
  <p>Group: <%= link_to @resource.group.topic, @resource.group %></p>
  <br>

</div>

<div class="row">
  <div class="col-md-8">
    <% if @resource.link[0..4] == "https" %>
    <button href="#" id="show_hide">Show/Hide Resource Pane </button>
    <div id="externalSiteContent" width="600">
      <iframe src="<%= @resource.link %>" width="600" height="400" style="border:medium double rgb(0, 0, 0)">
      </iframe>
    </div>
    <% else %>
      <p>Due to legal restrictions, we cannot display this resource here. Please use the link above to open it in a new tab.</p>
    <% end %>
  </div>


  <div class="col-md-4">

    <h3>Comments</h3>
    <ul class="comment-container">
      <% @resource.comments.each do |comment| %>
          <%= render 'comments/comment', {comment: comment} %>
      <% end %>
    </ul>
   
   <% if current_user.groups.include?(@resource.group) %>
      <%= form_for @comment, remote: true, html: {id: "new-comment-js"} do |f| %>
      <div class="form-group">
        <%= f.text_area :content, class: "form-control" %>
        <%= f.hidden_field :user_id, value: current_user.id %>
        <%= f.hidden_field :resource_id, value: @resource.id %>
      </div>
        <%= f.submit "Add Comment", class: "btn btn-default"%>
      <% end %>
      <br>
      <%= link_to "Send Comments to PDF", resource_path(@resource, format: :pdf), class: "btn btn-info" %>
      <br>
    </div>
  <% end %>

    
</div>